name: Il2CppInspector Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: Il2CppInspector.sln  # The solution file in the root directory.

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive  # Ensures all submodules are fetched and initialized.

    - name: Install .NET Core 3.1 Runtime
      run: |
        choco install dotnetcore-sdk --version=3.1.426 -y
        choco install dotnetcore-runtime --version=3.1.32 -y
        echo "C:\Program Files\dotnet" >> $GITHUB_PATH

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: |
          ./bin/${{ matrix.configuration }}/  # This is the default build output path
