name: Build and Publish .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the code and initialize submodules
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    # Install .NET Core 3.1 SDK and Runtime with retry logic
    - name: Install .NET Core 3.1 Runtime
      run: |
        choco install dotnetcore-sdk --version=3.1.426 -y
        choco install dotnetcore-runtime --version=3.1.32 -y
        echo "C:\Program Files\dotnet" >> $GITHUB_PATH
        
    # Setup .NET SDK

    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore Il2CppInspector.sln

    # Build the solution
    - name: Build the solution
      run: dotnet build Il2CppInspector.sln --configuration Release

    # Publish the application (CLI and GUI)
    - name: Publish the application
      run: |
        dotnet publish Il2CppInspector.sln -c Release

    # Upload the build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: |
          Il2CppInspector/Il2CppInspector.CLI/bin/Release/netcoreapp3.0/win-x64/publish/Il2CppInspector.exe
          Il2CppInspector/Il2CppInspector.GUI/bin/Release/netcoreapp3.1/win-x64/publish/Il2CppInspector.exe
